name: Deploy Synapse Workspace

on:
  push:
    branches:
      - main
    paths:
      - "notebooks/**"
      - "synapse/**"
      - ".github/workflows/deploy-synapse.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Synapse Deployment
      uses: Azure/synapse-deployment@v1.6.0
      with:
        TargetWorkspaceName: "parthworkspace"
        ResourceGroupName: "charitha-network"
        TemplateFile: "./synapse/template.json"
        ParametersFile: "./synapse/parameters.json"
